version: "3.8"

services:
  app:
    image: app
    container_name: app
    build: app
    restart: always  
    ports:
      - "8880:80"
    depends_on:
      - "server"

  server:
    image: server
    container_name: server
    build: server
    restart: always
    ports:
      - "8080:8080"

  caddy:
    image: caddy
    container_name: caddy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - "app"
      - "server" 
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config: